#!/bin/bash

IFS=$'\n'

function check_dependency() {
    local programs=(sponge)

    for prog in ${programs[@]}; do
        type sponge &> /dev/null

        if [[ $? != 0 ]]; then 
            echo "Please install moreutils package."
            exit
        fi
    done
}


function convert_encoding() {
    : ""
    local file=$1
    local encode=$(file -bi "$file" | cut -d ";" -f2-)

    case $encode in 
        #check if they are utf skip them and else state change them to utf
        *[uU][tT][fF]*)
        echo "${orange}skiping $file..."
        continue
        ;;
    *)
        echo "${green}Fixing $file..."
        iconv -f WINDOWS-1256 -t utf-8 "$file" | sponge "$file"  > /dev/null
        ;;
    esac
}


function main() {
    local files=$1
    if [[ -z $files ]]; then
        echo "Reading subtitles from current directory..."
        files=$(ls ./*srt ./*SRT 2>/dev/null)

        if [[ -z "$files" ]]; then
            echo "Subtitle not found!"
            exit 1
        fi

    fi

    for file in $files; do 
        convert_encoding $file
    done

    echo "Done!"
}

main $1
